version: '2'
services:
    postgres:
        image: geodan/gost-db
        environment:
            - POSTGRES_DB=gost
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        command: ["-c", "shared_buffers=256MB", "-c", "max_connections=200"]
        volumes:
            - postgres:/var/lib/postgresql/data
    gost:
        image: geodan/gost
        depends_on:
            - postgres
        ports:
            - "8095:8080"
        environment:
            - GOST_DB_HOST=postgres
            - GOST_SERVER_MAX_ENTITIES=10000
            - GOST_MQTT_ENABLED=false
    faker:
        image: docker.linksmart.eu/ogc-st/faker
        # build:
        #     context: .
        depends_on:
            - gost
        # volumes:
        #     - ./src:/home/app

volumes:
    postgres: {}