version: '2'
services:
    gost-db:
        image: geodan/gost-db
        environment:
            - POSTGRES_DB=gost
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    gost:
        image: geodan/gost
        depends_on:
            - gost-db
        ports:
            - "8095:8080"
        environment:
            - GOST_DB_HOST=gost-db
            - GOST_SERVER_MAX_ENTITIES=1000
            - GOST_MQTT_ENABLED=false
    dashboard:
        image: geodan/gost-dashboard
        ports:
          - "8090:8080"
        depends_on:
            - gost
    faker:
        image: docker.linksmart.eu/ogc-st/faker
        # build:
        #     context: .
        depends_on:
            - gost
            - gost-db
        volumes:
            - ./src:/home/app
        working_dir: /home/app
        command: python faker.py
        environment:
            - PYTHONUNBUFFERED=0
