version: '2'
services:
    # node-red:
    #     image: nodered/node-red-docker
    #     volumes:
    #         - nodered:/data
    #     ports:
    #         - "1880:1880"
    # mosquitto:
    #     image: toke/mosquitto
    #     volumes:
    #         - mosquitto_data:/mqtt/data
    #         - mosquitto_conf:/mqtt/config:ro
    #     ports:
    #         - "1883:1883"
    #         - "9001:9001"
    gost-db:
        image: geodan/gost-db:0.5
        volumes:
            - postgis:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: gost
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
    gost:
        image: geodan/gost:0.5
        depends_on:
            # - mosquitto
            - gost-db
        ports:
            - "8080:8080"
        environment:
            gost_db_host: gost-db
            gost_mqtt_host: mosquitto
            GOST_SERVER_MAX_ENTITIES: 1000
    dashboard:
        image: geodan/gost-dashboard:0.5
        ports:
          - "8090:8080"
        depends_on:
            - gost
    dummy-stream:
        image: ogc/datafaker
        depends_on:
            - gost
        # tty: true
        volumes:
            - ./src:/home/app
        working_dir: /home/app
        command: python faker.py
volumes:
    postgis: {}
    nodered: {}
    mosquitto_data: {}
    mosquitto_conf: {}
