version: '2'
services:
    gost-db:
        image: geodan/gost-db:0.5
        environment:
            POSTGRES_DB: gost
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
    gost:
        image: geodan/gost:0.5
        depends_on:
            - gost-db
        ports:
            - "8095:8080"
        environment:
            gost_db_host: gost-db
            GOST_SERVER_MAX_ENTITIES: 1000
            GOST_SERVER_EXTERNAL_URI: http://localhost:8095
    dashboard:
        image: geodan/gost-dashboard:0.5
        ports:
          - "8090:8080"
        depends_on:
            - gost
    faker:
        image: docker.linksmart.eu/ogc-st/faker
        # build:
        #     context: .
        depends_on:
            - gost
        volumes:
            - ./src:/home/app
        working_dir: /home/app
        command: python faker.py
        environment:
            - PYTHONUNBUFFERED=0
