version: '2'
services:
    postgres:
        image: geodan/gost-db
        environment:
            - POSTGRES_DB=gost
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        command: ["-c", "shared_buffers=256MB", "-c", "max_connections=200"]
        volumes:
            - postgres:/var/lib/postgresql/data
    gost:
        image: geodan/gost
        depends_on:
            - postgres
        ports:
            - "8095:8080"
        environment:
            - GOST_DB_HOST=postgres
            - GOST_SERVER_MAX_ENTITIES=10000
            - GOST_MQTT_ENABLED=false
            - GOST_LOG_VERBOSE_FLAG=true
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "10"
    faker:
        image: docker.linksmart.eu/ogc-st/faker
        # build:
        #     context: .
        depends_on:
            - gost
        environment:
            - GOST=http://gost:8080/v1.0
            - GOSTDB=postgres
            - GOSTDB_PORT=5432
        # volumes:
        #     - ./src:/home/app

volumes:
    postgres: {}
